name: Python packaging for learning

on:
    push:
      branches: main
    pull_request:
      branches: main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code contents in the repository
        uses: actions/checkout@v4

      - name: Create ZIP archive
        shell: cmd
        run: |
          7z a repo-package.zip . -xr!.git

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: repo-package
          path: repo-package.zip

      - name: Create or update GitHub Release for reusable link
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest Package
          files: repo-package.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}