name: Python packaging for learning

on:
    push:
      branches: main
    pull_request:
      branches: main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code contents in the repository
        uses: actions/checkout@v4
      - name: Create RAR archive
        shell: cmd
        run: |
          set RAR_PATH="C:\Program Files\WinRAR\rar.exe"
          if not exist %RAR_PATH% (
            echo WinRAR not found
            exit /b 1
          )
          %RAR_PATH% a -r repo-package.rar *

      - name: Upload RAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: repo-rar-package
          path: repo-package.rar

      - name: Output download link
        run: |
          echo Artifact download link:
          echo https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}